"use strict";
database.languages = [
{name: "Aarakocra", rarity: "Exotic", script: "None", source: "MM"},
{name: "Abanasinian", rarity: "Standard", script: "Common", source: "DSotDQ"},
{name: "Abyssal", rarity: "Exotic", script: "Infernal", source: "PHB"},
{name: "Celestial", rarity: "Exotic", script: "Celestial", source: "PHB"},
{name: "Common", rarity: "Standard", script: "Common", source: "PHB"},
{name: "Daelkyr", rarity: "Exotic", script: "Daelkyr", source: "ERLW"},
{name: "Deep Speech", rarity: "Exotic", script: "None", source: "PHB"},
{name: "Draconic", rarity: "Exotic", script: "Draconic", source: "PHB"},
{name: "Druidic", rarity: "Secret", script: "Secret", source: "PHB"},
{name: "Dwarvish", rarity: "Standard", script: "Dwarvish", source: "PHB"},
{name: "Elvish", rarity: "Standard", script: "Elvish", source: "PHB"},
{name: "Ergot", rarity: "Standard", script: "Common", source: "DSotDQ"},
{name: "Giant", rarity: "Standard", script: "Dwarvish", source: "PHB"},
{name: "Gith", rarity: "Exotic", script: "Tir'su", source: "MM"},
{name: "Gnomish", rarity: "Standard", script: "Dwarvish", source: "PHB"},
{name: "Goblin", rarity: "Standard", script: "Dwarvish", source: "PHB"},
{name: "Halfling", rarity: "Standard", script: "Common", source: "PHB"},
{name: "Infernal", rarity: "Exotic", script: "Infernal", source: "PHB"},
{name: "Istarian", rarity: "Rare", script: "Istarian", source: "DSotDQ"},
{name: "Kenderspeak", rarity: "Standard", script: "Common", source: "DSotDQ"},
{name: "Kharolian", rarity: "Standard", script: "Common", source: "DSotDQ"},
{name: "Khur", rarity: "Standard", script: "Istarian", source: "DSotDQ"},
{name: "Kothian", rarity: "Rare", script: "Kothian", source: "DSotDQ"},
{name: "Kraul", rarity: "Standard", script: "Kraul", source: "GGR"},
{name: "Loxodon", rarity: "Standard", script: "Elvish", source: "GGR"},
{name: "Merfolk", rarity: "Standard", script: "Merfolk", source: "GGR"},
{name: "Minotaur", rarity: "Standard", script: "Minotaur", source: "GGR"},
{name: "Nerakese", rarity: "Rare", script: "Istarian", source: "DSotDQ"},
{name: "Nordmaarian", rarity: "Standard", script: "Istarian", source: "DSotDQ"},
{name: "Ogre", rarity: "Rare", script: "Ogre", source: "DSotDQ"},
{name: "Orc", rarity: "Standard", script: "Dwarvish", source: "PHB"},
{name: "Primordial", rarity: "Exotic", script: "Dwarvish", source: "PHB"},
{name: "Quori", rarity: "Exotic", script: "Quori", source: "ERLW"},
{name: "Riedran", rarity: "Standard", script: "Common", source: "ERLW"},
{name: "Solamnic", rarity: "Standard", script: "Common", source: "DSotDQ"},
{name: "Sphinx", rarity: "Standard", script: "None", source: "GGR"},
{name: "Sylvan", rarity: "Exotic", script: "Elvish", source: "PHB"},
{name: "Thieves' Cant", rarity: "Secret", script: "Secret", source: "PHB"},
{name: "Thri-kreen", rarity: "Exotic", script: "None", source: "MM"},
{name: "Undercommon", rarity: "Exotic", script: "Elvish", source: "PHB"},
{name: "Vedalken", rarity: "Standard", script: "Vedalken", source: "GGR"},
];