"use strict";
database.spells = [
{name: "Abi-Dalzim's Horrid Wilting", level: 8, ritual: false, school: "N", source: "XGE"},
{name: "Absorb Elements", level: 1, ritual: false, school: "A", source: "XGE"},
{name: "Acid Splash", level: 0, ritual: false, school: "C", source: "PHB"},
{name: "Aganazzar's Scorcher", level: 2, ritual: false, school: "Ev", source: "XGE"},
{name: "Aid", level: 2, ritual: false, school: "A", source: "PHB"},
{name: "Air Bubble", level: 2, ritual: false, school: "C", source: "AAG"},
{name: "Alarm", level: 1, ritual: true, school: "A", source: "PHB"},
{name: "Alter Self", level: 2, ritual: false, school: "T", source: "PHB"},
{name: "Animal Friendship", level: 1, ritual: false, school: "En", source: "PHB"},
{name: "Animal Messenger", level: 2, ritual: true, school: "En", source: "PHB"},
{name: "Animal Shapes", level: 8, ritual: false, school: "T", source: "PHB"},
{name: "Animate Dead", level: 3, ritual: false, school: "N", source: "PHB"},
{name: "Animate Objects", level: 5, ritual: false, school: "T", source: "PHB"},
{name: "Antilife Shell", level: 5, ritual: false, school: "A", source: "PHB"},
{name: "Antimagic Field", level: 8, ritual: false, school: "A", source: "PHB"},
{name: "Antipathy/Sympathy", level: 8, ritual: false, school: "En", source: "PHB"},
{name: "Arcane Eye", level: 4, ritual: false, school: "D", source: "PHB"},
{name: "Arcane Gate", level: 6, ritual: false, school: "C", source: "PHB"},
{name: "Arcane Lock", level: 2, ritual: false, school: "A", source: "PHB"},
{name: "Armor of Agathys", level: 1, ritual: false, school: "A", source: "PHB"},
{name: "Arms of Hadar", level: 1, ritual: false, school: "C", source: "PHB"},
{name: "Ashardalon's Stride", level: 3, ritual: false, school: "T", source: "FTD"},
{name: "Astral Projection", level: 9, ritual: false, school: "N", source: "PHB"},
{name: "Augury", level: 2, ritual: true, school: "D", source: "PHB"},
{name: "Aura of Life", level: 4, ritual: false, school: "A", source: "PHB"},
{name: "Aura of Purity", level: 4, ritual: false, school: "A", source: "PHB"},
{name: "Aura of Vitality", level: 3, ritual: false, school: "Ev", source: "PHB"},
{name: "Awaken", level: 5, ritual: false, school: "T", source: "PHB"},
{name: "Bane", level: 1, ritual: false, school: "En", source: "PHB"},
{name: "Banishing Smite", level: 5, ritual: false, school: "A", source: "PHB"},
{name: "Banishment", level: 4, ritual: false, school: "A", source: "PHB"},
{name: "Barkskin", level: 2, ritual: false, school: "T", source: "PHB"},
{name: "Beacon of Hope", level: 3, ritual: false, school: "A", source: "PHB"},
{name: "Beast Bond", level: 1, ritual: false, school: "D", source: "XGE"},
{name: "Beast Sense", level: 2, ritual: true, school: "D", source: "PHB"},
{name: "Bestow Curse", level: 3, ritual: false, school: "N", source: "PHB"},
{name: "Bigby's Hand", level: 5, ritual: false, school: "Ev", source: "PHB"},
{name: "Blade Barrier", level: 6, ritual: false, school: "Ev", source: "PHB"},
{name: "Blade of Disaster", level: 9, ritual: false, school: "C", source: "TCE"},
{name: "Blade Ward", level: 0, ritual: false, school: "A", source: "PHB"},
{name: "Bless", level: 1, ritual: false, school: "En", source: "PHB"},
{name: "Blight", level: 4, ritual: false, school: "N", source: "PHB"},
{name: "Blinding Smite", level: 3, ritual: false, school: "Ev", source: "PHB"},
{name: "Blindness/Deafness", level: 2, ritual: false, school: "N", source: "PHB"},
{name: "Blink", level: 3, ritual: false, school: "T", source: "PHB"},
{name: "Blur", level: 2, ritual: false, school: "I", source: "PHB"},
{name: "Bones of the Earth", level: 6, ritual: false, school: "T", source: "XGE"},
{name: "Booming Blade", level: 0, ritual: false, school: "Ev", source: "TCE"},
{name: "Borrowed Knowledge", level: 2, ritual: false, school: "D", source: "SCC"},
{name: "Branding Smite", level: 2, ritual: false, school: "Ev", source: "PHB"},
{name: "Burning Hands", level: 1, ritual: false, school: "Ev", source: "PHB"},
{name: "Call Lightning", level: 3, ritual: false, school: "C", source: "PHB"},
{name: "Calm Emotions", level: 2, ritual: false, school: "En", source: "PHB"},
{name: "Catapult", level: 1, ritual: false, school: "T", source: "XGE"},
{name: "Catnap", level: 3, ritual: false, school: "En", source: "XGE"},
{name: "Cause Fear", level: 1, ritual: false, school: "N", source: "XGE"},
{name: "Ceremony", level: 1, ritual: true, school: "A", source: "XGE"},
{name: "Chain Lightning", level: 6, ritual: false, school: "Ev", source: "PHB"},
{name: "Chaos Bolt", level: 1, ritual: false, school: "Ev", source: "XGE"},
{name: "Charm Monster", level: 4, ritual: false, school: "En", source: "XGE"},
{name: "Charm Person", level: 1, ritual: false, school: "En", source: "PHB"},
{name: "Chill Touch", level: 0, ritual: false, school: "N", source: "PHB"},
{name: "Chromatic Orb", level: 1, ritual: false, school: "Ev", source: "PHB"},
{name: "Circle of Death", level: 6, ritual: false, school: "N", source: "PHB"},
{name: "Circle of Power", level: 5, ritual: false, school: "A", source: "PHB"},
{name: "Clairvoyance", level: 3, ritual: false, school: "D", source: "PHB"},
{name: "Clone", level: 8, ritual: false, school: "N", source: "PHB"},
{name: "Cloud of Daggers", level: 2, ritual: false, school: "C", source: "PHB"},
{name: "Cloudkill", level: 5, ritual: false, school: "C", source: "PHB"},
{name: "Color Spray", level: 1, ritual: false, school: "I", source: "PHB"},
{name: "Command", level: 1, ritual: false, school: "En", source: "PHB"},
{name: "Commune", level: 5, ritual: true, school: "D", source: "PHB"},
{name: "Commune with Nature", level: 5, ritual: true, school: "D", source: "PHB"},
{name: "Compelled Duel", level: 1, ritual: false, school: "En", source: "PHB"},
{name: "Comprehend Languages", level: 1, ritual: true, school: "D", source: "PHB"},
{name: "Compulsion", level: 4, ritual: false, school: "En", source: "PHB"},
{name: "Cone of Cold", level: 5, ritual: false, school: "Ev", source: "PHB"},
{name: "Confusion", level: 4, ritual: false, school: "En", source: "PHB"},
{name: "Conjure Animals", level: 3, ritual: false, school: "C", source: "PHB"},
{name: "Conjure Barrage", level: 3, ritual: false, school: "C", source: "PHB"},
{name: "Conjure Celestial", level: 7, ritual: false, school: "C", source: "PHB"},
{name: "Conjure Elemental", level: 5, ritual: false, school: "C", source: "PHB"},
{name: "Conjure Fey", level: 6, ritual: false, school: "C", source: "PHB"},
{name: "Conjure Minor Elementals", level: 4, ritual: false, school: "C", source: "PHB"},
{name: "Conjure Volley", level: 5, ritual: false, school: "C", source: "PHB"},
{name: "Conjure Woodland Beings", level: 4, ritual: false, school: "C", source: "PHB"},
{name: "Contact Other Plane", level: 5, ritual: true, school: "D", source: "PHB"},
{name: "Contagion", level: 5, ritual: false, school: "N", source: "PHB"},
{name: "Contingency", level: 6, ritual: false, school: "Ev", source: "PHB"},
{name: "Continual Flame", level: 2, ritual: false, school: "Ev", source: "PHB"},
{name: "Control Flames", level: 0, ritual: false, school: "T", source: "XGE"},
{name: "Control Water", level: 4, ritual: false, school: "T", source: "PHB"},
{name: "Control Weather", level: 8, ritual: false, school: "T", source: "PHB"},
{name: "Control Winds", level: 5, ritual: false, school: "T", source: "XGE"},
{name: "Cordon of Arrows", level: 2, ritual: false, school: "T", source: "PHB"},
{name: "Counterspell", level: 3, ritual: false, school: "A", source: "PHB"},
{name: "Create Bonfire", level: 0, ritual: false, school: "C", source: "XGE"},
{name: "Create Food and Water", level: 3, ritual: false, school: "C", source: "PHB"},
{name: "Create Homunculus", level: 6, ritual: false, school: "T", source: "XGE"},
{name: "Create Magen", level: 7, ritual: false, school: "T", source: "IDRotF"},
{name: "Create or Destroy Water", level: 1, ritual: false, school: "T", source: "PHB"},
{name: "Create Spelljamming Helm", level: 5, ritual: false, school: "T", source: "AAG"},
{name: "Create Undead", level: 6, ritual: false, school: "N", source: "PHB"},
{name: "Creation", level: 5, ritual: false, school: "I", source: "PHB"},
{name: "Crown of Madness", level: 2, ritual: false, school: "En", source: "PHB"},
{name: "Crown of Stars", level: 7, ritual: false, school: "Ev", source: "XGE"},
{name: "Crusader's Mantle", level: 3, ritual: false, school: "Ev", source: "PHB"},
{name: "Cure Wounds", level: 1, ritual: false, school: "Ev", source: "PHB"},
{name: "Dancing Lights", level: 0, ritual: false, school: "Ev", source: "PHB"},
{name: "Danse Macabre", level: 5, ritual: false, school: "N", source: "XGE"},
{name: "Dark Star", level: 8, ritual: false, school: "Ev", source: "EGW"},
{name: "Darkness", level: 2, ritual: false, school: "Ev", source: "PHB"},
{name: "Darkvision", level: 2, ritual: false, school: "T", source: "PHB"},
{name: "Dawn", level: 5, ritual: false, school: "Ev", source: "XGE"},
{name: "Daylight", level: 3, ritual: false, school: "Ev", source: "PHB"},
{name: "Death Ward", level: 4, ritual: false, school: "A", source: "PHB"},
{name: "Delayed Blast Fireball", level: 7, ritual: false, school: "Ev", source: "PHB"},
{name: "Demiplane", level: 8, ritual: false, school: "C", source: "PHB"},
{name: "Destructive Wave", level: 5, ritual: false, school: "Ev", source: "PHB"},
{name: "Detect Evil and Good", level: 1, ritual: false, school: "D", source: "PHB"},
{name: "Detect Magic", level: 1, ritual: true, school: "D", source: "PHB"},
{name: "Detect Poison and Disease", level: 1, ritual: true, school: "D", source: "PHB"},
{name: "Detect Thoughts", level: 2, ritual: false, school: "D", source: "PHB"},
{name: "Dimension Door", level: 4, ritual: false, school: "C", source: "PHB"},
{name: "Disguise Self", level: 1, ritual: false, school: "I", source: "PHB"},
{name: "Disintegrate", level: 6, ritual: false, school: "T", source: "PHB"},
{name: "Dispel Evil and Good", level: 5, ritual: false, school: "A", source: "PHB"},
{name: "Dispel Magic", level: 3, ritual: false, school: "A", source: "PHB"},
{name: "Dissonant Whispers", level: 1, ritual: false, school: "En", source: "PHB"},
{name: "Distort Value", level: 1, ritual: false, school: "I", source: "AI"},
{name: "Divination", level: 4, ritual: true, school: "D", source: "PHB"},
{name: "Divine Favor", level: 1, ritual: false, school: "Ev", source: "PHB"},
{name: "Divine Word", level: 7, ritual: false, school: "Ev", source: "PHB"},
{name: "Dominate Beast", level: 4, ritual: false, school: "En", source: "PHB"},
{name: "Dominate Monster", level: 8, ritual: false, school: "En", source: "PHB"},
{name: "Dominate Person", level: 5, ritual: false, school: "En", source: "PHB"},
{name: "Draconic Transformation", level: 7, ritual: false, school: "T", source: "FTD"},
{name: "Dragon's Breath", level: 2, ritual: false, school: "T", source: "XGE"},
{name: "Drawmij's Instant Summons", level: 6, ritual: true, school: "C", source: "PHB"},
{name: "Dream", level: 5, ritual: false, school: "I", source: "PHB"},
{name: "Dream of the Blue Veil", level: 7, ritual: false, school: "C", source: "TCE"},
{name: "Druid Grove", level: 6, ritual: false, school: "A", source: "XGE"},
{name: "Druidcraft", level: 0, ritual: false, school: "T", source: "PHB"},
{name: "Dust Devil", level: 2, ritual: false, school: "C", source: "XGE"},
{name: "Earth Tremor", level: 1, ritual: false, school: "Ev", source: "XGE"},
{name: "Earthbind", level: 2, ritual: false, school: "T", source: "XGE"},
{name: "Earthquake", level: 8, ritual: false, school: "Ev", source: "PHB"},
{name: "Eldritch Blast", level: 0, ritual: false, school: "Ev", source: "PHB"},
{name: "Elemental Bane", level: 4, ritual: false, school: "T", source: "XGE"},
{name: "Elemental Weapon", level: 3, ritual: false, school: "T", source: "PHB"},
{name: "Encode Thoughts", level: 0, ritual: false, school: "En", source: "GGR"},
{name: "Enemies Abound", level: 3, ritual: false, school: "En", source: "XGE"},
{name: "Enervation", level: 5, ritual: false, school: "N", source: "XGE"},
{name: "Enhance Ability", level: 2, ritual: false, school: "T", source: "PHB"},
{name: "Enlarge/Reduce", level: 2, ritual: false, school: "T", source: "PHB"},
{name: "Ensnaring Strike", level: 1, ritual: false, school: "C", source: "PHB"},
{name: "Entangle", level: 1, ritual: false, school: "C", source: "PHB"},
{name: "Enthrall", level: 2, ritual: false, school: "En", source: "PHB"},
{name: "Erupting Earth", level: 3, ritual: false, school: "T", source: "XGE"},
{name: "Etherealness", level: 7, ritual: false, school: "T", source: "PHB"},
{name: "Evard's Black Tentacles", level: 4, ritual: false, school: "C", source: "PHB"},
{name: "Expeditious Retreat", level: 1, ritual: false, school: "T", source: "PHB"},
{name: "Eyebite", level: 6, ritual: false, school: "N", source: "PHB"},
{name: "Fabricate", level: 4, ritual: false, school: "T", source: "PHB"},
{name: "Faerie Fire", level: 1, ritual: false, school: "Ev", source: "PHB"},
{name: "False Life", level: 1, ritual: false, school: "N", source: "PHB"},
{name: "Far Step", level: 5, ritual: false, school: "C", source: "XGE"},
{name: "Fast Friends", level: 3, ritual: false, school: "En", source: "AI"},
{name: "Fear", level: 3, ritual: false, school: "I", source: "PHB"},
{name: "Feather Fall", level: 1, ritual: false, school: "T", source: "PHB"},
{name: "Feeblemind", level: 8, ritual: false, school: "En", source: "PHB"},
{name: "Feign Death", level: 3, ritual: true, school: "N", source: "PHB"},
{name: "Find Familiar", level: 1, ritual: true, school: "C", source: "PHB"},
{name: "Find Greater Steed", level: 4, ritual: false, school: "C", source: "XGE"},
{name: "Find Steed", level: 2, ritual: false, school: "C", source: "PHB"},
{name: "Find the Path", level: 6, ritual: false, school: "D", source: "PHB"},
{name: "Find Traps", level: 2, ritual: false, school: "D", source: "PHB"},
{name: "Finger of Death", level: 7, ritual: false, school: "N", source: "PHB"},
{name: "Fire Bolt", level: 0, ritual: false, school: "Ev", source: "PHB"},
{name: "Fire Shield", level: 4, ritual: false, school: "Ev", source: "PHB"},
{name: "Fire Storm", level: 7, ritual: false, school: "Ev", source: "PHB"},
{name: "Fireball", level: 3, ritual: false, school: "Ev", source: "PHB"},
{name: "Fizban's Platinum Shield", level: 6, ritual: false, school: "A", source: "FTD"},
{name: "Flame Arrows", level: 3, ritual: false, school: "T", source: "XGE"},
{name: "Flame Blade", level: 2, ritual: false, school: "Ev", source: "PHB"},
{name: "Flame Strike", level: 5, ritual: false, school: "Ev", source: "PHB"},
{name: "Flaming Sphere", level: 2, ritual: false, school: "C", source: "PHB"},
{name: "Flesh to Stone", level: 6, ritual: false, school: "T", source: "PHB"},
{name: "Fly", level: 3, ritual: false, school: "T", source: "PHB"},
{name: "Fog Cloud", level: 1, ritual: false, school: "C", source: "PHB"},
{name: "Forbiddance", level: 6, ritual: true, school: "A", source: "PHB"},
{name: "Forcecage", level: 7, ritual: false, school: "Ev", source: "PHB"},
{name: "Foresight", level: 9, ritual: false, school: "D", source: "PHB"},
{name: "Fortune's Favor", level: 2, ritual: false, school: "D", source: "EGW"},
{name: "Freedom of Movement", level: 4, ritual: false, school: "A", source: "PHB"},
{name: "Friends", level: 0, ritual: false, school: "En", source: "PHB"},
{name: "Frost Fingers", level: 1, ritual: false, school: "Ev", source: "IDRotF"},
{name: "Frostbite", level: 0, ritual: false, school: "Ev", source: "XGE"},
{name: "Gaseous Form", level: 3, ritual: false, school: "T", source: "PHB"},
{name: "Gate", level: 9, ritual: false, school: "C", source: "PHB"},
{name: "Geas", level: 5, ritual: false, school: "En", source: "PHB"},
{name: "Gentle Repose", level: 2, ritual: true, school: "N", source: "PHB"},
{name: "Giant Insect", level: 4, ritual: false, school: "T", source: "PHB"},
{name: "Gift of Alacrity", level: 1, ritual: false, school: "D", source: "EGW"},
{name: "Gift of Gab", level: 2, ritual: false, school: "En", source: "AI"},
{name: "Glibness", level: 8, ritual: false, school: "T", source: "PHB"},
{name: "Globe of Invulnerability", level: 6, ritual: false, school: "A", source: "PHB"},
{name: "Glyph of Warding", level: 3, ritual: false, school: "A", source: "PHB"},
{name: "Goodberry", level: 1, ritual: false, school: "T", source: "PHB"},
{name: "Grasping Vine", level: 4, ritual: false, school: "C", source: "PHB"},
{name: "Gravity Fissure", level: 6, ritual: false, school: "Ev", source: "EGW"},
{name: "Gravity Sinkhole", level: 4, ritual: false, school: "Ev", source: "EGW"},
{name: "Grease", level: 1, ritual: false, school: "C", source: "PHB"},
{name: "Greater Invisibility", level: 4, ritual: false, school: "I", source: "PHB"},
{name: "Greater Restoration", level: 5, ritual: false, school: "A", source: "PHB"},
{name: "Green-Flame Blade", level: 0, ritual: false, school: "Ev", source: "TCE"},
{name: "Guardian of Faith", level: 4, ritual: false, school: "C", source: "PHB"},
{name: "Guardian of Nature", level: 4, ritual: false, school: "T", source: "XGE"},
{name: "Guards and Wards", level: 6, ritual: false, school: "A", source: "PHB"},
{name: "Guidance", level: 0, ritual: false, school: "D", source: "PHB"},
{name: "Guiding Bolt", level: 1, ritual: false, school: "Ev", source: "PHB"},
{name: "Gust", level: 0, ritual: false, school: "T", source: "XGE"},
{name: "Gust of Wind", level: 2, ritual: false, school: "Ev", source: "PHB"},
{name: "Hail of Thorns", level: 1, ritual: false, school: "C", source: "PHB"},
{name: "Hallow", level: 5, ritual: false, school: "Ev", source: "PHB"},
{name: "Hallucinatory Terrain", level: 4, ritual: false, school: "I", source: "PHB"},
{name: "Harm", level: 6, ritual: false, school: "N", source: "PHB"},
{name: "Haste", level: 3, ritual: false, school: "T", source: "PHB"},
{name: "Heal", level: 6, ritual: false, school: "Ev", source: "PHB"},
{name: "Healing Spirit", level: 2, ritual: false, school: "C", source: "XGE"},
{name: "Healing Word", level: 1, ritual: false, school: "Ev", source: "PHB"},
{name: "Heat Metal", level: 2, ritual: false, school: "T", source: "PHB"},
{name: "Hellish Rebuke", level: 1, ritual: false, school: "Ev", source: "PHB"},
{name: "Heroes' Feast", level: 6, ritual: false, school: "C", source: "PHB"},
{name: "Heroism", level: 1, ritual: false, school: "En", source: "PHB"},
{name: "Hex", level: 1, ritual: false, school: "En", source: "PHB"},
{name: "Hold Monster", level: 5, ritual: false, school: "En", source: "PHB"},
{name: "Hold Person", level: 2, ritual: false, school: "En", source: "PHB"},
{name: "Holy Aura", level: 8, ritual: false, school: "A", source: "PHB"},
{name: "Holy Weapon", level: 5, ritual: false, school: "Ev", source: "XGE"},
{name: "Hunger of Hadar", level: 3, ritual: false, school: "C", source: "PHB"},
{name: "Hunter's Mark", level: 1, ritual: false, school: "D", source: "PHB"},
{name: "Hypnotic Pattern", level: 3, ritual: false, school: "I", source: "PHB"},
{name: "Ice Knife", level: 1, ritual: false, school: "C", source: "XGE"},
{name: "Ice Storm", level: 4, ritual: false, school: "Ev", source: "PHB"},
{name: "Identify", level: 1, ritual: true, school: "D", source: "PHB"},
{name: "Illusory Dragon", level: 8, ritual: false, school: "I", source: "XGE"},
{name: "Illusory Script", level: 1, ritual: true, school: "I", source: "PHB"},
{name: "Immolation", level: 5, ritual: false, school: "Ev", source: "XGE"},
{name: "Immovable Object", level: 2, ritual: false, school: "T", source: "EGW"},
{name: "Imprisonment", level: 9, ritual: false, school: "A", source: "PHB"},
{name: "Incendiary Cloud", level: 8, ritual: false, school: "C", source: "PHB"},
{name: "Incite Greed", level: 3, ritual: false, school: "En", source: "AI"},
{name: "Infernal Calling", level: 5, ritual: false, school: "C", source: "XGE"},
{name: "Infestation", level: 0, ritual: false, school: "C", source: "XGE"},
{name: "Inflict Wounds", level: 1, ritual: false, school: "N", source: "PHB"},
{name: "Insect Plague", level: 5, ritual: false, school: "C", source: "PHB"},
{name: "Intellect Fortress", level: 3, ritual: false, school: "A", source: "TCE"},
{name: "Investiture of Flame", level: 6, ritual: false, school: "T", source: "XGE"},
{name: "Investiture of Ice", level: 6, ritual: false, school: "T", source: "XGE"},
{name: "Investiture of Stone", level: 6, ritual: false, school: "T", source: "XGE"},
{name: "Investiture of Wind", level: 6, ritual: false, school: "T", source: "XGE"},
{name: "Invisibility", level: 2, ritual: false, school: "I", source: "PHB"},
{name: "Invulnerability", level: 9, ritual: false, school: "A", source: "XGE"},
{name: "Jim's Glowing Coin", level: 2, ritual: false, school: "En", source: "AI"},
{name: "Jim's Magic Missile", level: 1, ritual: false, school: "Ev", source: "AI"},
{name: "Jump", level: 1, ritual: false, school: "T", source: "PHB"},
{name: "Kinetic Jaunt", level: 2, ritual: false, school: "T", source: "SCC"},
{name: "Knock", level: 2, ritual: false, school: "T", source: "PHB"},
{name: "Legend Lore", level: 5, ritual: false, school: "D", source: "PHB"},
{name: "Leomund's Secret Chest", level: 4, ritual: false, school: "C", source: "PHB"},
{name: "Leomund's Tiny Hut", level: 3, ritual: true, school: "Ev", source: "PHB"},
{name: "Lesser Restoration", level: 2, ritual: false, school: "A", source: "PHB"},
{name: "Levitate", level: 2, ritual: false, school: "T", source: "PHB"},
{name: "Life Transference", level: 3, ritual: false, school: "N", source: "XGE"},
{name: "Light", level: 0, ritual: false, school: "Ev", source: "PHB"},
{name: "Lightning Arrow", level: 3, ritual: false, school: "T", source: "PHB"},
{name: "Lightning Bolt", level: 3, ritual: false, school: "Ev", source: "PHB"},
{name: "Lightning Lure", level: 0, ritual: false, school: "Ev", source: "TCE"},
{name: "Locate Animals or Plants", level: 2, ritual: true, school: "D", source: "PHB"},
{name: "Locate Creature", level: 4, ritual: false, school: "D", source: "PHB"},
{name: "Locate Object", level: 2, ritual: false, school: "D", source: "PHB"},
{name: "Longstrider", level: 1, ritual: false, school: "T", source: "PHB"},
{name: "Maddening Darkness", level: 8, ritual: false, school: "Ev", source: "XGE"},
{name: "Maelstrom", level: 5, ritual: false, school: "Ev", source: "XGE"},
{name: "Mage Armor", level: 1, ritual: false, school: "A", source: "PHB"},
{name: "Mage Hand", level: 0, ritual: false, school: "C", source: "PHB"},
{name: "Magic Circle", level: 3, ritual: false, school: "A", source: "PHB"},
{name: "Magic Jar", level: 6, ritual: false, school: "N", source: "PHB"},
{name: "Magic Missile", level: 1, ritual: false, school: "Ev", source: "PHB"},
{name: "Magic Mouth", level: 2, ritual: true, school: "I", source: "PHB"},
{name: "Magic Stone", level: 0, ritual: false, school: "T", source: "XGE"},
{name: "Magic Weapon", level: 2, ritual: false, school: "T", source: "PHB"},
{name: "Magnify Gravity", level: 1, ritual: false, school: "T", source: "EGW"},
{name: "Major Image", level: 3, ritual: false, school: "I", source: "PHB"},
{name: "Mass Cure Wounds", level: 5, ritual: false, school: "Ev", source: "PHB"},
{name: "Mass Heal", level: 9, ritual: false, school: "Ev", source: "PHB"},
{name: "Mass Healing Word", level: 3, ritual: false, school: "Ev", source: "PHB"},
{name: "Mass Polymorph", level: 9, ritual: false, school: "T", source: "XGE"},
{name: "Mass Suggestion", level: 6, ritual: false, school: "En", source: "PHB"},
{name: "Maximilian's Earthen Grasp", level: 2, ritual: false, school: "T", source: "XGE"},
{name: "Maze", level: 8, ritual: false, school: "C", source: "PHB"},
{name: "Meld into Stone", level: 3, ritual: true, school: "T", source: "PHB"},
{name: "Melf's Acid Arrow", level: 2, ritual: false, school: "Ev", source: "PHB"},
{name: "Melf's Minute Meteors", level: 3, ritual: false, school: "Ev", source: "XGE"},
{name: "Mending", level: 0, ritual: false, school: "T", source: "PHB"},
{name: "Mental Prison", level: 6, ritual: false, school: "I", source: "XGE"},
{name: "Message", level: 0, ritual: false, school: "T", source: "PHB"},
{name: "Meteor Swarm", level: 9, ritual: false, school: "Ev", source: "PHB"},
{name: "Mighty Fortress", level: 8, ritual: false, school: "C", source: "XGE"},
{name: "Mind Blank", level: 8, ritual: false, school: "A", source: "PHB"},
{name: "Mind Sliver", level: 0, ritual: false, school: "En", source: "TCE"},
{name: "Mind Spike", level: 2, ritual: false, school: "D", source: "XGE"},
{name: "Minor Illusion", level: 0, ritual: false, school: "I", source: "PHB"},
{name: "Mirage Arcane", level: 7, ritual: false, school: "I", source: "PHB"},
{name: "Mirror Image", level: 2, ritual: false, school: "I", source: "PHB"},
{name: "Mislead", level: 5, ritual: false, school: "I", source: "PHB"},
{name: "Misty Step", level: 2, ritual: false, school: "C", source: "PHB"},
{name: "Modify Memory", level: 5, ritual: false, school: "En", source: "PHB"},
{name: "Mold Earth", level: 0, ritual: false, school: "T", source: "XGE"},
{name: "Moonbeam", level: 2, ritual: false, school: "Ev", source: "PHB"},
{name: "Mordenkainen's Faithful Hound", level: 4, ritual: false, school: "C", source: "PHB"},
{name: "Mordenkainen's Magnificent Mansion", level: 7, ritual: false, school: "C", source: "PHB"},
{name: "Mordenkainen's Private Sanctum", level: 4, ritual: false, school: "A", source: "PHB"},
{name: "Mordenkainen's Sword", level: 7, ritual: false, school: "Ev", source: "PHB"},
{name: "Motivational Speech", level: 3, ritual: false, school: "En", source: "AI"},
{name: "Move Earth", level: 6, ritual: false, school: "T", source: "PHB"},
{name: "Nathair's Mischief", level: 2, ritual: false, school: "I", source: "FTD"},
{name: "Negative Energy Flood", level: 5, ritual: false, school: "N", source: "XGE"},
{name: "Nondetection", level: 3, ritual: false, school: "A", source: "PHB"},
{name: "Nystul's Magic Aura", level: 2, ritual: false, school: "I", source: "PHB"},
{name: "Otiluke's Freezing Sphere", level: 6, ritual: false, school: "Ev", source: "PHB"},
{name: "Otiluke's Resilient Sphere", level: 4, ritual: false, school: "Ev", source: "PHB"},
{name: "Otto's Irresistible Dance", level: 6, ritual: false, school: "En", source: "PHB"},
{name: "Pass without Trace", level: 2, ritual: false, school: "A", source: "PHB"},
{name: "Passwall", level: 5, ritual: false, school: "T", source: "PHB"},
{name: "Phantasmal Force", level: 2, ritual: false, school: "I", source: "PHB"},
{name: "Phantasmal Killer", level: 4, ritual: false, school: "I", source: "PHB"},
{name: "Phantom Steed", level: 3, ritual: true, school: "I", source: "PHB"},
{name: "Planar Ally", level: 6, ritual: false, school: "C", source: "PHB"},
{name: "Planar Binding", level: 5, ritual: false, school: "A", source: "PHB"},
{name: "Plane Shift", level: 7, ritual: false, school: "C", source: "PHB"},
{name: "Plant Growth", level: 3, ritual: false, school: "T", source: "PHB"},
{name: "Poison Spray", level: 0, ritual: false, school: "C", source: "PHB"},
{name: "Polymorph", level: 4, ritual: false, school: "T", source: "PHB"},
{name: "Power Word Heal", level: 9, ritual: false, school: "Ev", source: "PHB"},
{name: "Power Word Kill", level: 9, ritual: false, school: "En", source: "PHB"},
{name: "Power Word Pain", level: 7, ritual: false, school: "En", source: "XGE"},
{name: "Power Word Stun", level: 8, ritual: false, school: "En", source: "PHB"},
{name: "Prayer of Healing", level: 2, ritual: false, school: "Ev", source: "PHB"},
{name: "Prestidigitation", level: 0, ritual: false, school: "T", source: "PHB"},
{name: "Primal Savagery", level: 0, ritual: false, school: "T", source: "XGE"},
{name: "Primordial Ward", level: 6, ritual: false, school: "A", source: "XGE"},
{name: "Prismatic Spray", level: 7, ritual: false, school: "Ev", source: "PHB"},
{name: "Prismatic Wall", level: 9, ritual: false, school: "A", source: "PHB"},
{name: "Produce Flame", level: 0, ritual: false, school: "C", source: "PHB"},
{name: "Programmed Illusion", level: 6, ritual: false, school: "I", source: "PHB"},
{name: "Project Image", level: 7, ritual: false, school: "I", source: "PHB"},
{name: "Protection from Energy", level: 3, ritual: false, school: "A", source: "PHB"},
{name: "Protection from Evil and Good", level: 1, ritual: false, school: "A", source: "PHB"},
{name: "Protection from Poison", level: 2, ritual: false, school: "A", source: "PHB"},
{name: "Psychic Scream", level: 9, ritual: false, school: "En", source: "XGE"},
{name: "Pulse Wave", level: 3, ritual: false, school: "Ev", source: "EGW"},
{name: "Purify Food and Drink", level: 1, ritual: true, school: "T", source: "PHB"},
{name: "Pyrotechnics", level: 2, ritual: false, school: "T", source: "XGE"},
{name: "Raise Dead", level: 5, ritual: false, school: "N", source: "PHB"},
{name: "Rary's Telepathic Bond", level: 5, ritual: true, school: "D", source: "PHB"},
{name: "Raulothim's Psychic Lance", level: 4, ritual: false, school: "En", source: "FTD"},
{name: "Ravenous Void", level: 9, ritual: false, school: "Ev", source: "EGW"},
{name: "Ray of Enfeeblement", level: 2, ritual: false, school: "N", source: "PHB"},
{name: "Ray of Frost", level: 0, ritual: false, school: "Ev", source: "PHB"},
{name: "Ray of Sickness", level: 1, ritual: false, school: "N", source: "PHB"},
{name: "Reality Break", level: 8, ritual: false, school: "C", source: "EGW"},
{name: "Regenerate", level: 7, ritual: false, school: "T", source: "PHB"},
{name: "Reincarnate", level: 5, ritual: false, school: "T", source: "PHB"},
{name: "Remove Curse", level: 3, ritual: false, school: "A", source: "PHB"},
{name: "Resistance", level: 0, ritual: false, school: "A", source: "PHB"},
{name: "Resurrection", level: 7, ritual: false, school: "N", source: "PHB"},
{name: "Reverse Gravity", level: 7, ritual: false, school: "T", source: "PHB"},
{name: "Revivify", level: 3, ritual: false, school: "N", source: "PHB"},
{name: "Rime's Binding Ice", level: 2, ritual: false, school: "Ev", source: "FTD"},
{name: "Rope Trick", level: 2, ritual: false, school: "T", source: "PHB"},
{name: "Sacred Flame", level: 0, ritual: false, school: "Ev", source: "PHB"},
{name: "Sanctuary", level: 1, ritual: false, school: "A", source: "PHB"},
{name: "Sapping Sting", level: 0, ritual: false, school: "N", source: "EGW"},
{name: "Scatter", level: 6, ritual: false, school: "C", source: "XGE"},
{name: "Scorching Ray", level: 2, ritual: false, school: "Ev", source: "PHB"},
{name: "Scrying", level: 5, ritual: false, school: "D", source: "PHB"},
{name: "Searing Smite", level: 1, ritual: false, school: "Ev", source: "PHB"},
{name: "See Invisibility", level: 2, ritual: false, school: "D", source: "PHB"},
{name: "Seeming", level: 5, ritual: false, school: "I", source: "PHB"},
{name: "Sending", level: 3, ritual: false, school: "Ev", source: "PHB"},
{name: "Sequester", level: 7, ritual: false, school: "T", source: "PHB"},
{name: "Shadow Blade", level: 2, ritual: false, school: "I", source: "XGE"},
{name: "Shadow of Moil", level: 4, ritual: false, school: "N", source: "XGE"},
{name: "Shape Water", level: 0, ritual: false, school: "T", source: "XGE"},
{name: "Shapechange", level: 9, ritual: false, school: "T", source: "PHB"},
{name: "Shatter", level: 2, ritual: false, school: "Ev", source: "PHB"},
{name: "Shield", level: 1, ritual: false, school: "A", source: "PHB"},
{name: "Shield of Faith", level: 1, ritual: false, school: "A", source: "PHB"},
{name: "Shillelagh", level: 0, ritual: false, school: "T", source: "PHB"},
{name: "Shocking Grasp", level: 0, ritual: false, school: "Ev", source: "PHB"},
{name: "Sickening Radiance", level: 4, ritual: false, school: "Ev", source: "XGE"},
{name: "Silence", level: 2, ritual: true, school: "I", source: "PHB"},
{name: "Silent Image", level: 1, ritual: false, school: "I", source: "PHB"},
{name: "Silvery Barbs", level: 1, ritual: false, school: "En", source: "SCC"},
{name: "Simulacrum", level: 7, ritual: false, school: "I", source: "PHB"},
{name: "Skill Empowerment", level: 5, ritual: false, school: "T", source: "XGE"},
{name: "Skywrite", level: 2, ritual: true, school: "T", source: "XGE"},
{name: "Sleep", level: 1, ritual: false, school: "En", source: "PHB"},
{name: "Sleet Storm", level: 3, ritual: false, school: "C", source: "PHB"},
{name: "Slow", level: 3, ritual: false, school: "T", source: "PHB"},
{name: "Snare", level: 1, ritual: false, school: "A", source: "XGE"},
{name: "Snilloc's Snowball Swarm", level: 2, ritual: false, school: "Ev", source: "XGE"},
{name: "Soul Cage", level: 6, ritual: false, school: "N", source: "XGE"},
{name: "Spare the Dying", level: 0, ritual: false, school: "N", source: "PHB"},
{name: "Speak with Animals", level: 1, ritual: true, school: "D", source: "PHB"},
{name: "Speak with Dead", level: 3, ritual: false, school: "N", source: "PHB"},
{name: "Speak with Plants", level: 3, ritual: false, school: "T", source: "PHB"},
{name: "Spider Climb", level: 2, ritual: false, school: "T", source: "PHB"},
{name: "Spike Growth", level: 2, ritual: false, school: "T", source: "PHB"},
{name: "Spirit Guardians", level: 3, ritual: false, school: "C", source: "PHB"},
{name: "Spirit Shroud", level: 3, ritual: false, school: "N", source: "TCE"},
{name: "Spiritual Weapon", level: 2, ritual: false, school: "Ev", source: "PHB"},
{name: "Staggering Smite", level: 4, ritual: false, school: "Ev", source: "PHB"},
{name: "Steel Wind Strike", level: 5, ritual: false, school: "C", source: "XGE"},
{name: "Stinking Cloud", level: 3, ritual: false, school: "C", source: "PHB"},
{name: "Stone Shape", level: 4, ritual: false, school: "T", source: "PHB"},
{name: "Stoneskin", level: 4, ritual: false, school: "A", source: "PHB"},
{name: "Storm of Vengeance", level: 9, ritual: false, school: "C", source: "PHB"},
{name: "Storm Sphere", level: 4, ritual: false, school: "Ev", source: "XGE"},
{name: "Suggestion", level: 2, ritual: false, school: "En", source: "PHB"},
{name: "Summon Aberration", level: 4, ritual: false, school: "C", source: "TCE"},
{name: "Summon Beast", level: 2, ritual: false, school: "C", source: "TCE"},
{name: "Summon Celestial", level: 5, ritual: false, school: "C", source: "TCE"},
{name: "Summon Construct", level: 4, ritual: false, school: "C", source: "TCE"},
{name: "Summon Draconic Spirit", level: 5, ritual: false, school: "C", source: "FTD"},
{name: "Summon Elemental", level: 4, ritual: false, school: "C", source: "TCE"},
{name: "Summon Fey", level: 3, ritual: false, school: "C", source: "TCE"},
{name: "Summon Fiend", level: 6, ritual: false, school: "C", source: "TCE"},
{name: "Summon Greater Demon", level: 4, ritual: false, school: "C", source: "XGE"},
{name: "Summon Lesser Demons", level: 3, ritual: false, school: "C", source: "XGE"},
{name: "Summon Shadowspawn", level: 3, ritual: false, school: "C", source: "TCE"},
{name: "Summon Undead", level: 3, ritual: false, school: "N", source: "TCE"},
{name: "Sunbeam", level: 6, ritual: false, school: "Ev", source: "PHB"},
{name: "Sunburst", level: 8, ritual: false, school: "Ev", source: "PHB"},
{name: "Swift Quiver", level: 5, ritual: false, school: "T", source: "PHB"},
{name: "Sword Burst", level: 0, ritual: false, school: "C", source: "TCE"},
{name: "Symbol", level: 7, ritual: false, school: "A", source: "PHB"},
{name: "Synaptic Static", level: 5, ritual: false, school: "En", source: "XGE"},
{name: "Tasha's Caustic Brew", level: 1, ritual: false, school: "Ev", source: "TCE"},
{name: "Tasha's Hideous Laughter", level: 1, ritual: false, school: "En", source: "PHB"},
{name: "Tasha's Mind Whip", level: 2, ritual: false, school: "En", source: "TCE"},
{name: "Tasha's Otherworldly Guise", level: 6, ritual: false, school: "T", source: "TCE"},
{name: "Telekinesis", level: 5, ritual: false, school: "T", source: "PHB"},
{name: "Telepathy", level: 8, ritual: false, school: "Ev", source: "PHB"},
{name: "Teleport", level: 7, ritual: false, school: "C", source: "PHB"},
{name: "Teleportation Circle", level: 5, ritual: false, school: "C", source: "PHB"},
{name: "Temple of the Gods", level: 7, ritual: false, school: "C", source: "XGE"},
{name: "Temporal Shunt", level: 5, ritual: false, school: "T", source: "EGW"},
{name: "Tenser's Floating Disk", level: 1, ritual: true, school: "C", source: "PHB"},
{name: "Tenser's Transformation", level: 6, ritual: false, school: "T", source: "XGE"},
{name: "Tether Essence", level: 7, ritual: false, school: "N", source: "EGW"},
{name: "Thaumaturgy", level: 0, ritual: false, school: "T", source: "PHB"},
{name: "Thorn Whip", level: 0, ritual: false, school: "T", source: "PHB"},
{name: "Thunder Step", level: 3, ritual: false, school: "C", source: "XGE"},
{name: "Thunderclap", level: 0, ritual: false, school: "Ev", source: "XGE"},
{name: "Thunderous Smite", level: 1, ritual: false, school: "Ev", source: "PHB"},
{name: "Thunderwave", level: 1, ritual: false, school: "Ev", source: "PHB"},
{name: "Tidal Wave", level: 3, ritual: false, school: "C", source: "XGE"},
{name: "Time Ravage", level: 9, ritual: false, school: "N", source: "EGW"},
{name: "Time Stop", level: 9, ritual: false, school: "T", source: "PHB"},
{name: "Tiny Servant", level: 3, ritual: false, school: "T", source: "XGE"},
{name: "Toll the Dead", level: 0, ritual: false, school: "N", source: "XGE"},
{name: "Tongues", level: 3, ritual: false, school: "D", source: "PHB"},
{name: "Transmute Rock", level: 5, ritual: false, school: "T", source: "XGE"},
{name: "Transport via Plants", level: 6, ritual: false, school: "C", source: "PHB"},
{name: "Tree Stride", level: 5, ritual: false, school: "C", source: "PHB"},
{name: "True Polymorph", level: 9, ritual: false, school: "T", source: "PHB"},
{name: "True Resurrection", level: 9, ritual: false, school: "N", source: "PHB"},
{name: "True Seeing", level: 6, ritual: false, school: "D", source: "PHB"},
{name: "True Strike", level: 0, ritual: false, school: "D", source: "PHB"},
{name: "Tsunami", level: 8, ritual: false, school: "C", source: "PHB"},
{name: "Unseen Servant", level: 1, ritual: true, school: "C", source: "PHB"},
{name: "Vampiric Touch", level: 3, ritual: false, school: "N", source: "PHB"},
{name: "Vicious Mockery", level: 0, ritual: false, school: "En", source: "PHB"},
{name: "Vitriolic Sphere", level: 4, ritual: false, school: "Ev", source: "XGE"},
{name: "Vortex Warp", level: 2, ritual: false, school: "C", source: "SCC"},
{name: "Wall of Fire", level: 4, ritual: false, school: "Ev", source: "PHB"},
{name: "Wall of Force", level: 5, ritual: false, school: "Ev", source: "PHB"},
{name: "Wall of Ice", level: 6, ritual: false, school: "Ev", source: "PHB"},
{name: "Wall of Light", level: 5, ritual: false, school: "Ev", source: "XGE"},
{name: "Wall of Sand", level: 3, ritual: false, school: "Ev", source: "XGE"},
{name: "Wall of Stone", level: 5, ritual: false, school: "Ev", source: "PHB"},
{name: "Wall of Thorns", level: 6, ritual: false, school: "C", source: "PHB"},
{name: "Wall of Water", level: 3, ritual: false, school: "Ev", source: "XGE"},
{name: "Warding Bond", level: 2, ritual: false, school: "A", source: "PHB"},
{name: "Warding Wind", level: 2, ritual: false, school: "Ev", source: "XGE"},
{name: "Water Breathing", level: 3, ritual: true, school: "T", source: "PHB"},
{name: "Water Walk", level: 3, ritual: true, school: "T", source: "PHB"},
{name: "Watery Sphere", level: 4, ritual: false, school: "C", source: "XGE"},
{name: "Web", level: 2, ritual: false, school: "C", source: "PHB"},
{name: "Weird", level: 9, ritual: false, school: "I", source: "PHB"},
{name: "Whirlwind", level: 7, ritual: false, school: "Ev", source: "XGE"},
{name: "Wind Walk", level: 6, ritual: false, school: "T", source: "PHB"},
{name: "Wind Wall", level: 3, ritual: false, school: "Ev", source: "PHB"},
{name: "Wish", level: 9, ritual: false, school: "C", source: "PHB"},
{name: "Witch Bolt", level: 1, ritual: false, school: "Ev", source: "PHB"},
{name: "Wither and Bloom", level: 2, ritual: false, school: "N", source: "SCC"},
{name: "Word of Radiance", level: 0, ritual: false, school: "Ev", source: "XGE"},
{name: "Word of Recall", level: 6, ritual: false, school: "C", source: "PHB"},
{name: "Wrath of Nature", level: 5, ritual: false, school: "Ev", source: "XGE"},
{name: "Wrathful Smite", level: 1, ritual: false, school: "Ev", source: "PHB"},
{name: "Wristpocket", level: 2, ritual: true, school: "C", source: "EGW"},
{name: "Zephyr Strike", level: 1, ritual: false, school: "T", source: "XGE"},
{name: "Zone of Truth", level: 2, ritual: false, school: "En", source: "PHB"},
];